#-----------------------------------
# UVM LIB
#-----------------------------------
UVM_LIB_DEFS :=
UVM_LIB_DEFS += UVM_NO_DPI
EXPANDED_UVM_LIB_DEFS = $(foreach x,$(UVM_LIB_DEFS),+define+$(x))

UVM_LIB_INCS :=
UVM_LIB_INCS += $(UVM_HOME)/src
UVM_LIB_INCS += $(UVM_HOME)/src/macros
EXPANDED_UVM_LIB_INCS = $(foreach x,$(UVM_LIB_INCS),+incdir+$(x))

UVM_LIB_SRCS :=
UVM_LIB_SRCS += $(UVM_HOME)/src/uvm_pkg.sv

#-----------------------------------
# MODEL LIB
#-----------------------------------
MODEL_LIB_DEFS :=
MODEL_LIB_DEFS += MODELSIM

MODEL_LIB_INCS :=
MODEL_LIB_INCS += $(UVM_HOME)/src
MODEL_LIB_INCS += $(UVM_HOME)/src/macros
MODEL_LIB_INCS += $(PRJ_ROOT)/rtl
MODEL_LIB_INCS += $(PRJ_ROOT)/rtl/soc

MODEL_LIB_SRCS :=
MODEL_LIB_SRCS += $(PRJ_ROOT)/rtl/soc/soc_top.sv
MODEL_LIB_SRCS += $(PRJ_ROOT)/rtl/alu.sv

MODEL_LIB_LIBLIST :=
MODEL_LIB_LIBLIST += uvm_lib
EXPANDED_MODEL_LIB_LIBLIST = $(foreach x,$(MODEL_LIB_LIBLIST),-liblist $(x))

EXPANDED_MODEL_LIB_DEFS = $(foreach x,$(MODEL_LIB_DEFS),+define+$(x))
EXPANDED_MODEL_LIB_INCS = $(foreach x,$(MODEL_LIB_INCS),+incdir+$(x))

#-----------------------------------
# TB & TESTS ENV
#-----------------------------------
TEST_LIB_DEFS :=
TEST_LIB_DEFS += MODELSIM
TEST_LIB_DEFS += CUSTOM_REPORT_SERVER

TEST_LIB_INCS :=
TEST_LIB_INCS += $(UVM_HOME)/src
TEST_LIB_INCS += $(UVM_HOME)/src/macros
TEST_LIB_INCS += $(PRJ_ROOT)/rtl/soc
TEST_LIB_INCS += $(PRJ_ROOT)/tb

TEST_LIB_SRCS :=
TEST_LIB_SRCS += $(PRJ_ROOT)/tb/top_tb.sv

TEST_LIB_LIBLIST :=
TEST_LIB_LIBLIST += uvm_lib
TEST_LIB_LIBLIST += alu_lib
EXPANDED_TEST_LIB_LIBLIST = $(foreach x,$(TEST_LIB_LIBLIST),-liblist $(x))

EXPANDED_TEST_LIB_DEFS = $(foreach x,$(TEST_LIB_DEFS),+define+$(x))
EXPANDED_TEST_LIB_INCS = $(foreach x,$(TEST_LIB_INCS),+incdir+$(x))

TB_TOP = top_tb
TESTNAME = test_demo

define MODEL_BUILD

// NOTE: this file was generated by:
// $(PRJ_ROOT)/Makefile.src.mk

-top $(TB_TOP)

####################################
##lib=uvm_lib
+dvt_init+$(DVT_COMPATIBILITY_MODE)
-work uvm_lib
$(foreach x,$(VLOG_OPTS),
$(x))
$(foreach x,$(UVM_LIB_DEFS),
+define+$(x))
$(foreach x,$(UVM_LIB_INCS),
+incdir+$(abspath $(x)))
$(foreach x,$(UVM_LIB_SRCS),
$(abspath $(x)))

####################################

##lib=model_lib
+dvt_init+$(DVT_COMPATIBILITY_MODE)
-work model_lib
$(foreach x,$(VLOG_OPTS),
$(x))
$(foreach x,$(MODEL_LIB_DEFS),
+define+$(x))
$(foreach x,$(MODEL_LIB_LIBLIST),
-liblist $(x))
$(foreach x,$(MODEL_LIB_INCS),
+incdir+$(abspath $(x)))
$(foreach x,$(MODEL_LIB_SRCS),
$(abspath $(x)))

##lib=test_lib
+dvt_init+$(DVT_COMPATIBILITY_MODE)
-work test_lib
$(foreach x,$(VLOG_OPTS),
$(x))
$(foreach x,$(TEST_LIB_DEFS),
+define+$(x))
$(foreach x,$(TEST_LIB_LIBLIST),
-liblist $(x))
$(foreach x,$(TEST_LIB_INCS),
+incdir+$(abspath $(x)))
$(foreach x,$(TEST_LIB_SRCS),
$(abspath $(x)))

endef
export MODEL_BUILD

define RUNCMD_BUILD

// NOTE: this file was generated by:
// $(PRJ_ROOT)/Makefile.src.mk

+UVM_TESTNAME=$(TESTNAME)
+dvtx_native_jimpl_uvm

endef
export RUNCMD_BUILD

###################################
# QuestaSim Options and Targets
###################################
VLOG_OPTS :=
VLOG_OPTS += -64

VSIM_OPTS :=
VSIM_OPTS += -c
VSIM_OPTS += -64
VSIM_OPTS += -dpicpppath /usr/bin/gcc

VSIM_SCRIPTS := sim/questa/scripts

# FIXME: need to figure out how to point to local UVM version
#qrun:
#	qrun -quiet $(EXPANDED_MODEL_LIB_DEFS) $(MODEL_LIB_SRCS) $(EXPANDED_TEST_LIB_DEFS) $(TEST_LIB_SRCS)

vlog:
	vlog -work work $(VLOG_OPTS) $(EXPANDED_UVM_LIB_DEFS) $(EXPANDED_UVM_LIB_INCS) $(UVM_LIB_SRCS) 
	vlog -work work $(VLOG_OPTS) $(EXPANDED_MODEL_LIB_DEFS) $(EXPANDED_MODEL_LIB_INCS) $(MODEL_LIB_SRCS)
	vlog -work work $(VLOG_OPTS) $(EXPANDED_TEST_LIB_DEFS) $(EXPANDED_TEST_LIB_INCS) $(TEST_LIB_SRCS)

vsim: vlog
	vsim $(VSIM_OPTS) +UVM_TESTNAME=$(TESTNAME) $(TB_TOP) -do $(VSIM_SCRIPTS)/run.do

verilate:
	@echo "-- Verilator hello-world simple binary example"
	@echo "-- VERILATE & BUILD --------"
	$(VERILATOR) --binary -j 0 $(TEST_LIB_SRCS) $(MODEL_LIB_SRCS)
#	$(VERILATOR) -Wall --cc alu.sv --exe alu_tb.sv --build
	@echo "-- RUN ---------------------"
	obj_dir/Valu_tb
	@echo "-- DONE --------------------"
	@echo "Note: Once this example is understood, see examples/make_hello_c."
	@echo "Note: See also https://verilator.org/guide/latest/examples.html"
